### ISSUE TITLE
Waiting for Podfile

### ISSUE THREAD

**Issue by Praphin** [DrGodCarl/hashids-objc#1]
Please add podfile for the project.

**Comment by DrGodCarl** [comment]
I ran in to some issues with git submodules the first time around. I'll set aside some time this week to fiddle with it.

**Comment by Praphin** [comment]
Thanks for the update.

**Comment by DrGodCarl** [comment]
Alright, I've published the Podspec and updated the readme with instructions for using it in your podfile. Should be good to go!

**Comment by Praphin** [comment]
Thanks.
Getting specification error,

[!] Unable to find a specification for `NNLHashids`

<img width="1278" alt="screen shot 2017-09-25 at 11 09 08 am" src="https://user-images.githubusercontent.com/6714897/30793821-029afcd0-a1e2-11e7-83f5-b11b66e01b7a.png">

**Comment by DrGodCarl** [comment]
Do you have access to [this repository](https://github.com/DrGodCarl/hashids.c)? You should, since it's public, but it looks like whatever you're dealing with is the result of something being unable to find a git submodule. Take a look at [this](http://www.geero.net/2014/06/using-submodules-in-cocoapods-sourced-from-git/) and try modifying your podfile accordingly. Not sure why it worked for me out of the box but not you. Looks like it might even be a problem with your public key that you use for cloning from GitHub? Those are my thoughts right now. I'll poke around tomorrow evening if you haven't figured it out by then.
